"""auto created transaction table

Revision ID: 1059b32d249b
Revises: 98ce947e00c1
Create Date: 2023-05-16 21:14:17.080698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1059b32d249b'
down_revision = '98ce947e00c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transction_id', sa.String(), nullable=False),
    sa.Column('isAdded', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('transaction_medium', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('is_rejected_by_admin', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transction_id')
    )
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('True'), nullable=False))
    op.add_column('users', sa.Column('role', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.drop_constraint('users_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_id_fkey', 'users', 'coins', ['id'], ['user_id'])
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_verified')
    op.drop_table('transactions')
    # ### end Alembic commands ###
