"""refferal table added

Revision ID: 15eb8625bd4c
Revises: ace9e634945f
Create Date: 2023-06-12 22:53:52.727869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15eb8625bd4c'
down_revision = 'ace9e634945f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refferals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refferal_user_id', sa.Integer(), nullable=True),
    sa.Column('reffered_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('is_success', sa.Boolean(), server_default=sa.text('True'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['reffered_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('refferal', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refferal')
    op.drop_table('refferals')
    # ### end Alembic commands ###
