"""auto created otp table

Revision ID: 3a93b35eb096
Revises: 1059b32d249b
Create Date: 2023-05-17 02:28:27.761559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a93b35eb096'
down_revision = '1059b32d249b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_email'),
    sa.UniqueConstraint('user_email')
    )
    op.add_column('coins', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False))
    op.create_unique_constraint(None, 'coins', ['user_id'])
    op.add_column('transactions', sa.Column('screenshot_url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'screenshot_url')
    op.drop_constraint(None, 'coins', type_='unique')
    op.drop_column('coins', 'created_at')
    op.drop_table('otps')
    # ### end Alembic commands ###
