"""lottery_notice table added

Revision ID: 426a445e4a59
Revises: 613d40b42629
Create Date: 2023-07-01 15:47:50.148527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426a445e4a59'
down_revision = '613d40b42629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery_notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notice_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lottery_notice')
    # ### end Alembic commands ###
