"""transaction medium table added

Revision ID: 514f4601f45a
Revises: 4822a9339cb0
Create Date: 2023-06-19 21:36:17.924808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514f4601f45a'
down_revision = '4822a9339cb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_mediums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medium_title', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_mediums')
    # ### end Alembic commands ###
