"""lucky_draw_coin_value table added

Revision ID: 613d40b42629
Revises: 514f4601f45a
Create Date: 2023-06-29 13:23:31.435597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613d40b42629'
down_revision = '514f4601f45a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lucky_draw_coin_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin_value', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lucky_draw_coin_values')
    # ### end Alembic commands ###
