"""lottery winner user_id unique constraint removed

Revision ID: 6595868a80bf
Revises: be429e36bd4b
Create Date: 2023-07-03 22:09:21.822747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6595868a80bf'
down_revision = 'be429e36bd4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lottery_winners_user_id_key', 'lottery_winners', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('lottery_winners_user_id_key', 'lottery_winners', ['user_id'])
    # ### end Alembic commands ###
