"""winner table added

Revision ID: 6cae3adb7067
Revises: c81fefb1c6c4
Create Date: 2023-05-28 01:03:19.236617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cae3adb7067'
down_revision = 'c81fefb1c6c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('lottery_winners',
    # sa.Column('lottery_token_no', sa.Integer(), nullable=False),
    # sa.Column('position', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
   
    # sa.PrimaryKeyConstraint('lottery_token_no'),
    # sa.UniqueConstraint('lottery_token_no'),

    # sa.ForeignKeyConstraint(['position'], ['lottery_prize.rank_no'], ondelete='CASCADE'),
    # sa.UniqueConstraint('position'),

    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa .UniqueConstraint('user_id'))
    

    # op.create_foreign_key('lottery_users_user_id_fkey', 'lottery', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('lottery_winners')
    # op.drop_constraint('lottery_users_user_id_fkey', 'lottery', type_='foreignkey')
    # ### end Alembic commands ###
    pass
