"""lottery winner created_at coulm added

Revision ID: 902ffb098930
Revises: af3c693f0407
Create Date: 2023-07-04 21:15:54.326437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902ffb098930'
down_revision = 'af3c693f0407'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lottery_winners', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lottery_winners', 'created_at')
    # ### end Alembic commands ###
