"""auto generate user to coin table foreigh key

Revision ID: 98ce947e00c1
Revises: ec3a9ac829e4
Create Date: 2023-05-14 01:48:41.156709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ce947e00c1'
down_revision = 'ec3a9ac829e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'coins', ['id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
