"""auto delete fKey from OTPs

Revision ID: a6cdc18c2a2a
Revises: 3a93b35eb096
Create Date: 2023-05-17 11:08:39.686879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cdc18c2a2a'
down_revision = '3a93b35eb096'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'otps', ['user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otps', type_='unique')
    # ### end Alembic commands ###
