"""user verification default value changed

Revision ID: ace9e634945f
Revises: a74597c17dd2
Create Date: 2023-06-02 16:19:50.523260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace9e634945f'
down_revision = 'a74597c17dd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'lottery_winners', ['lottery_token_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lottery_winners', type_='unique')
    # ### end Alembic commands ###
