"""lottery winner token fkey constraint removed

Revision ID: af3c693f0407
Revises: 6595868a80bf
Create Date: 2023-07-04 20:20:23.363741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3c693f0407'
down_revision = '6595868a80bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lottery_winner_token_lottery_fkey', 'lottery_winners', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lottery_winner_token_lottery_fkey', 'lottery_winners', 'lottery', ['lottery_token_no'], ['lottery_token'], ondelete='CASCADE')
    # ### end Alembic commands ###
