"""lottery winner token fkey added

Revision ID: be429e36bd4b
Revises: 426a445e4a59
Create Date: 2023-07-01 19:32:13.574506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be429e36bd4b'
down_revision = '426a445e4a59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lottery_winner_token_lottery_fkey', 'lottery_winners', 'lottery', ['lottery_token_no'], ['lottery_token'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lottery_winner_token_lottery_fkey', 'lottery_winners', type_='foreignkey')
    # ### end Alembic commands ###
