"""auto generate coins table

Revision ID: ec3a9ac829e4
Revises: 3ef111f6b12d
Create Date: 2023-05-13 23:35:19.818638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3a9ac829e4'
down_revision = '3ef111f6b12d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('num_of_coins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('coin_type', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('multiplication_factor', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins')
    # ### end Alembic commands ###
