"""auto created lottery and lottery_prize table

Revision ID: f1fcc424342a
Revises: a6cdc18c2a2a
Create Date: 2023-05-27 19:42:35.159104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fcc424342a'
down_revision = 'a6cdc18c2a2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery_prize',
    sa.Column('rank_no', sa.Integer(), nullable=False),
    sa.Column('prize_money', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rank_no'),
    sa.UniqueConstraint('rank_no')
    )
    op.create_table('lottery',
    sa.Column('lottery_token', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_winner', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('lottery_coin_price', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('lottery_token'),
    sa.UniqueConstraint('lottery_token')
    )
    op.add_column('users', sa.Column('phone_no', sa.String(), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['phone_no'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'phone_no')
    op.drop_table('lottery')
    op.drop_table('lottery_prize')
    # ### end Alembic commands ###
