"""auto lottery user_id fkey Cascade added

Revision ID: fd115c0e6278
Revises: 6cae3adb7067
Create Date: 2023-05-28 17:29:33.779054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd115c0e6278'
down_revision = '6cae3adb7067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lottery_user_id_fkey', 'lottery', type_='foreignkey')
    op.create_foreign_key(None, 'lottery', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lottery', type_='foreignkey')
    op.create_foreign_key('lottery_user_id_fkey', 'lottery', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
